### ISSUE TITLE
AndroidTv/ShieldTv

### ISSUE THREAD

**Issue by ControllerShieldTv** [BradyBrenot/huestacean#115]
Hi, Just want to say Ive been using Huestacean On my Shield and it work pretty damn good. Currently using Hue Lightsrip and PlayBars behind tv . The only issue I'm having is ,, once I shut it off completly  and restart it another day I have to reset it the way I like it .   Is this app still being worked /updated ?  ...... Thanks in advanced

**Comment by BradyBrenot** [comment]
It was on hold for months because I designed myself into a hole, but I'm starting it up again. Preferences are going to be handled and saved differently, it might help, not sure yet what's causing these Android issue.

**Comment by BradyBrenot** [comment]
Rolling all Android TV / Fire TV issues into #126
