### ISSUE TITLE
Smooth transitions

### ISSUE THREAD

**Issue by BradyBrenot** [BradyBrenot/huestacean#16]
Optional transition smoothing. Per-light. All lights would have it enabled by default, but peripheral lights would be more sluggish to avoid sudden unsettling changes, per Philips' advice.

Will need to be careful with default values, it still needs to be responsive and "wow", but not distracting. Will need to watch content with lots of cuts...

**Comment by riahc3** [comment]
Glad you already thought of this. A smoother transition of lights would be nice (the option at least)

**Comment by BradyBrenot** [comment]
I think the effect in bdacc80 is _decent enough_ to expose it to the GUI at the very least.

**Comment by BradyBrenot** [comment]
I'm now thinking this is slightly blocked by #14 ; the issues with the naive approach to color averaging are more apparent when you try to smooth things out.
