### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by BradyBrenot** [BradyBrenot/huestacean#21]
- [x] Running on Android
- [x] LGPL implications?
- [x] Screen sync
- [ ] Test Android TV AVD
- [ ] In Play Store
- [ ] Camera sync
- [ ] SSDP detection of PC installs
- [ ] Sync settings with PC
- [ ] Run scenes, effect, etc. off PC

**Comment by Lackmake** [comment]
Please also take AndroidTV (Shield, Sony/Philips TVs) into consideration

**Comment by JurajNyiri** [comment]
Tested on Android TV... BRAVIA 2015 KDL-43W807C 6.0.1
No monitor detected in sync and when clicked start sync crashes.

**Comment by BradyBrenot** [comment]
@JurajNyiri is it connected to a bridge?

![image](https://user-images.githubusercontent.com/632920/38219954-0be52d0c-36a6-11e8-8e73-77b263bab4b9.png)

What version of Android is installed?

Any chance of getting logcat output when the crash happens? I've never tried this from Android TV, given that I don't have an Android TV device, but it should be like:

https://stackoverflow.com/questions/39834242/sony-bravia-android-tv-how-to-enable-retrieve-adb-logcat-logs

So far there's reports from Sony X900E, Nvidia Shield, and Fire TV working without a crash, and I've tested 5.1 with an emulator.

**Comment by JurajNyiri** [comment]
Yes it was linked ... and it was on 6.0.1 I got a prompt and ran an update so unfortunately I will not be able to provide log...

I updated it to 7.0... issue is gone, first it wasnt working - I started sync, it went to main menu automatically and did nothing else than changing color to blue and sitting on it... Then I let it stay in the app for a while and switched through about, sync and link pages until it started looping through colors under "monitor". Then I started sync and it works - not in YT but it works everywhere else I tried - menus, kodi, which is the main thing.

Awesome work, thank you! :)

**Comment by tallguy425** [comment]
@JurajNyiri did you ever find a solution for this?  I just installed this on my Sony Bravia TV and works until it crashes. When it’s working, it’s great!   

I see that Philips released their own app today for Mac and Windows.  I may try that out tonight.

**Comment by BradyBrenot** [comment]
Folded into #126
