### ISSUE TITLE
Idea: Xbox Implementation

### ISSUE THREAD

**Issue by klodeckel1990** [BradyBrenot/huestacean#28]
I saw you're a game developer. Is there a way to perform screengrabbing on Xbox and run as Background App? That would be awesome.

**Comment by BradyBrenot** [comment]
I don't know if that's even possible (I've never done UWP development, on Xbox One or elsewhere), but more importantly I don't have an Xbox One so I wouldn't have any means of testing it, or for that matter much in the way of motivation -- I'm not sure, but UWP might be harder than Android support. Unless that changes I can't really do this, but maybe someone else will pick it up.

**Comment by jacoblb64** [comment]
Not quite sure if backgrounding an app is possible on the Xbox, but here's a workaround to get the lights syncing: You can use the Xbox app from a Win10 computer to stream the Xbox to your computer, then run Huestacean in the background. You can continue using your Xbox as normal and the lights will sync, albeit with a bit of delay depending on your internet.

**Comment by BradyBrenot** [comment]
Closing as this doesn't appear to actually be possible. If I'm wrong, will reopen.
