### ISSUE TITLE
DPI scaling and low resolutions, GUI is not usable

### ISSUE THREAD

**Issue by joostwestra** [BradyBrenot/huestacean#29]
First of all, great app. Works on my Windows machine.
However with my default settings a big portion of the controls fall of the screen. I think I have quite a typical setup for a use case like this:
 1920*1080 with 150% scaling so that I can read from the couch.
Would not mind if I need to change the scaling for setup. But starting the sync would be nice if that at least stays visible.

**Comment by BradyBrenot** [comment]
d3e8073 'fixes' by adding scrolling

**Comment by joostwestra** [comment]
impressed by the speed and the professionalism of the update management. Good work.
