### ISSUE TITLE
Investigate perf, especially on older hardware

### ISSUE THREAD

**Issue by BradyBrenot** [BradyBrenot/huestacean#31]
### Windows
 - Runs so well now I'm not even going to bother profiling it or anything.

### Mac OS
 - Performance problems. Investigating.
   - ~45 ms per frame. CPU load spikes, WindowServer goes up to 70-90% use.

**Comment by BradyBrenot** [comment]
So far:

On Windows/DX11
- GPU usage is way too high
- CPU usage is dominated by graphics driver

But sure if I can do anything about this DXGI screen cap performance, but one thing I *can* do is reduce the size of the texture we pull off the GPU, since we need to drop pixels to even use it on the CPU in a reasonable time anyways. So:

Reduce size of image before pulling off GPU, not after #36

**Comment by klodeckel1990** [comment]
Just tested it on the MacBook Pro 2015 with 2.7GHz Intel Core i5 and Intel Iris 7100 GPU, and there are significant performance problems. It is not possible to play a YouTube video and the whole system is jerking, also the Entertainment-Group is not synching very well.

**Comment by BradyBrenot** [comment]
macOS runs pretty poop generally. It may be the way screen_capture_light is grabbing the screen.

Developing on macOS is a bit of a pain for me, at the moment, but I'll have to just get over it.

**Comment by BradyBrenot** [comment]
Shoving this off. Maybe I'll look into it on the weekend.

**Comment by BradyBrenot** [comment]
macOS:

CGDisplayCreateImage does not appear to be intended for repeated capture of the screen. It's absolutely killing the OS.

Better methods:
- [How to capture screen activity to a movie file using AV Foundation on OS X 10.7 Lion and later](https://developer.apple.com/library/content/qa/qa1740/_index.html)
- [OpenGLCaptureToMovie](https://developer.apple.com/legacy/library/samplecode/OpenGLScreenCapture/Introduction/Intro.html)

**Comment by BradyBrenot** [comment]
Work for macOS in #62

Windows appears fine now that I'm resizing images before returning them from the GPU, so nothing to do there.
