### ISSUE TITLE
Suddenly stops working when playing game

### ISSUE THREAD

**Issue by theshorterbus** [BradyBrenot/huestacean#38]
Eg. Overwatch. It worked previously and suddenly it stopped working. It works in menu, etc. Then when I start a game the lights shut off and stop working. if I alt tab to the desktop, they work, but then alt tab again and they dont.

**Comment by Reaping666** [comment]
Just an idea:
Have you checked if Overwatch is running in "Windowed (Borderless)" or Fullscreen. Could be a problem with true fullscreen applications and Overwatch doing something strange on that side (don't know).
Might check it later on my side if I'm back home. Never tested overwatch with it until now.

Also, you are not running Razer Synapse with the new Hue support? Possibly not, just to make sure ;P
This started to do weird stuff with my lights when I tested it.

**Comment by Reaping666** [comment]
Sorry for the late reply.

Just tested the current release with Overwatch and both "Fullscreen" and "Fullscreen (Windowed) work perfectly for me. So I can't confirm your problem.

**Comment by theshorterbus** [comment]
I'll play around with more testing, and see if I can narrow it down. It was working. Oddly what I have noticed is that it only happens when an online match starts. I load up Overwatch, and even play practice range it works. Choose competitive or quick play whatever, as soon as the match loads in, the lights go black. windowed or borderless dont change it oddly.
