### ISSUE TITLE
Version 0.1a not working

### ISSUE THREAD

**Issue by Reaping666** [BradyBrenot/huestacean#39]
0,0 is working fine here.
After trying to update to version 0.1a, it looks like the screen capture isn't working anymore. When Visualize is on, the ppreview just shows random colors all over the image.
This does not happen with version 0.0.

GPU: GTX 1070

**Comment by theshorterbus** [comment]
same issue Ryzen 1700 and HD 7970

**Comment by BradyBrenot** [comment]
Well I don't have a single clue what went wrong there, the same thing happens to me, but not if I simply recompile from where the repo is right now (no other local changes). I'll just bundle up a new Release so it's clear what the good source is.
