### ISSUE TITLE
Test Linux

### ISSUE THREAD

**Issue by BradyBrenot** [BradyBrenot/huestacean#4]

**Comment by Perry3D** [comment]
Hi there, 
i tried to build huestacean under my arch installation.
I had to fix one file and added some missing libraries:
https://github.com/Perry3D/huestacean/commit/fd3f98fd4030e70f4eac8ee5a69f52dec103c2da
https://github.com/Perry3D/huestacean/commit/9c92464f5111079340cd4a9adc5325901b8427dd

It is working fine but is maybe a little bit slower than with my windows system.

**Comment by BradyBrenot** [comment]
Thanks! I pulled those changes in (788b2d5), looks good.

**Comment by Perry3D** [comment]
I am not sure if the libraries are needed for the mac and windows build. Maybe they should be added in a seperate linux section.
