### ISSUE TITLE
External interface to enable/disable the sync

### ISSUE THREAD

**Issue by joostwestra** [BradyBrenot/huestacean#40]
Maybe a nice enhancement:
To have an externally accessible  interface to enable or disable the sync from external sources.
Think of use cases such as Kodi/XBMC to only run the sync when a movie starts.
Or to allow the toggle from a domotica system. (OpenHab, domoticz etc.)

Possible interfaces:
MQTT
Http call

If you want help with this, let me know.

**Comment by gjniewenhuijse** [comment]
+1

**Comment by BradyBrenot** [comment]
Yeah if you can figure out how to / and implement this, it'd be a good help. I haven't really been thinking about CLI or server control yet, and the design's pretty straightforwardly attached to the QtQuick GUI...

**Comment by BradyBrenot** [comment]
I'd probably just go straight HTTP / JSON. It's going to mostly be doing this over the LAN and latency, throughput, CPU use shouldn't be too concerning.

**Comment by joostwestra** [comment]
Indeed latency and performance are not any issue at all I expect. HTTP / JSON would be fine I guess. Not to difficult to integrate with third parties.

**Comment by flatlined** [comment]
Really hoping control via command line parameters is an option in the future. From there pretty much any program that allows passing stuff through a terminal should be viable for basic control.

**Comment by BradyBrenot** [comment]
Relates to #69 ; if that's accomplished, adding additional frontends should be feasible. A CLI frontend is probably the only one I'd do myself though.

**Comment by BradyBrenot** [comment]
#128 - CLI
#127 - HTTP

#80 split Huestacean up to make it easier to have different main functions / start it without a GUI.

#122 uses QtRO to link the "Backend" from the "Frontend", letting me control Huestacean remotely and also opening the possibility of controlling local or remote instances from a CLI executable with ease.
