### ISSUE TITLE
Can't screen sync when using multiple monitors

### ISSUE THREAD

**Issue by Reaping666** [BradyBrenot/huestacean#42]
Hey,

don't know whats causing these problems but in the new version 1.0 I have the same problem like last time with 0.1.
Starting sync just gives random colors in preview and my lights turn black.

I'm sure you can fix it ;-D
Looking forward to the new features.

**Comment by BradyBrenot** [comment]
Weird. I did test it properly this time, not sure what I missed. In the meantime I've renamed the release to pretend I anticipated this ;)

**Comment by BradyBrenot** [comment]
This is probably going to end up being one of those things #23 would solve...

**Comment by BradyBrenot** [comment]
Any more info about your setup? Is it working in 0.2?

Unlike 0.1a I can't get 1.0 to fail. It could be down to resolution differences, or graphics card / IGP differences, or something else.

**Comment by Reaping666** [comment]
I'm running the following:

OS: Win10 Pro 64bit
GPU: 1070 GTX
DesktopRes: 2x 1920*1080

v0.2 was running fine and still is. Don't know whats causing it. Also I haven't updated any drivers nor Windows between 0.2 and 1.0.

**Comment by BradyBrenot** [comment]
Make sure you've got all the DLLs and other requirements in the directory with the built huestacean.exe; I use windeployqt to do that (the README talks about it). Otherwise, yeah, it'd be fantastic if you could manage to debug it. I just tried using two monitors and setting both to 1920x1080 but that didn't do anything either. I might have to get _creative_ with it later.

**Comment by BradyBrenot** [comment]
MMmmmm, does it look anything like this? I don't know what I did but it's stuck. Looking into it.
![image](https://user-images.githubusercontent.com/632920/36880456-ca59d55e-1d96-11e8-8edd-9b44e9765326.png)

**Comment by BradyBrenot** [comment]
@Reaping666 [v1.1](https://github.com/BradyBrenot/huestacean/releases/tag/v1.1) should fix this. Let me know how it goes. Thanks!

**Comment by Reaping666** [comment]
Works perfectly now again ;D
Awesome work!
