### ISSUE TITLE
Test Windows 7

### ISSUE THREAD

**Issue by BradyBrenot** [BradyBrenot/huestacean#5]
Test with a VM?

**Comment by AbraKabastard** [comment]
I'll be using this on a Windows 7 Machine. I will post any problems I encounter here.

**Comment by paul211b** [comment]
Did you get this working on Win7?  I tried last night.  I can connect to my bridge I can also see the entertainment configuration, however when you start sync just get a blue flashing box.  64bit.

**Comment by BradyBrenot** [comment]
Added an issue to track, #73. I'm not going to work on it though, so I've put a note in the README. PRs are welcome if anyone wants to.
