### ISSUE TITLE
Hotkey Toggle?

### ISSUE THREAD

**Issue by Dracrius** [BradyBrenot/huestacean#53]
Would you mind implementing a hotkey for enabling/disabling sync? This is a feature missing from every ambilight program I have found so far and it's driving me nuts. I don't even care if I can set my own as long as there is one as I would use it all the time and it'd also make coding up an OpenHAB toggle a lot easier as I'll be able to use Eventghost to turn sync ON and OFF and Eventghost can receive MQTT messages/commands from my OpenHAB. Thanks in advance as this would make my day!

*Edit
After confirming that the light's not being toggle able while Sync is active is an API issue I'd like to stress how amazing this would be to have! I'm in and out of my office all the time and I wont be able to use the new API at all if I don't have a quick way to turn sync on and off!

**Comment by BradyBrenot** [comment]
folding into duplicate #101
