### ISSUE TITLE
v2.0-alpha.1 Memory Leak

### ISSUE THREAD

**Issue by Dracrius** [BradyBrenot/huestacean#55]
I can only assume there is a memory leak when launched it will start at about 70mb and just start climbing as soon as you enable sync. Today I noticed it because I had left it open not even running/syncing over night and task manager showed it at something around 440mb (I'll estimate at most maybe an hour that sync was running between yesterday and today). After only about a minute I am already at 120mb and climbing since starting to type this with sync enabled. I love your app and its responsiveness but with the current cost of RAM and that I tend to get close to my 8gb when gaming I wouldn't be able to use your program for what I want it for which is my games. I can only assume you don't intend for it to be this hungry while syncing!

**Comment by BradyBrenot** [comment]
This is with 2.0-alpha.1, I'm guessing? I **definitely** introduced a memory leak into there, in a local change to screen_capture_lite; it's already been fixed upstream so I'll update that and it should be good.

**Comment by Dracrius** [comment]
Ok thanks I'll be watching the release page for a new build.

**Comment by BradyBrenot** [comment]
resolved in 51417e4

**Comment by BradyBrenot** [comment]
[Release v2.0-alpha.2](https://github.com/BradyBrenot/huestacean/releases/tag/v2.0-alpha.2) is up now

**Comment by Dracrius** [comment]
OMG I had to come back and comment because the difference is amazing! It now starts up at around 55mb but after running for about 5-10min it started to drop even though I had sync ON and it levels off at a consistent 24mb while running and dropping as low as 15mb with sync disabled. I am blown away by the difference and can't wait to see how this develops. Thanks Mate!
