### ISSUE TITLE
Android - Handle non touch based input

### ISSUE THREAD

**Issue by dtanquary** [BradyBrenot/huestacean#63]
It would be great to be able to try this out on an android device hooked up to my TV such as a fire TV or Android TV. I was able to install the latest build on my fire tv and open it, but I am not able to navigate or select anything using the firetv remote.

**Comment by BradyBrenot** [comment]
I'm not sure if Qt has any sort of built-in handling of Android TV. If it does it probably works like keyboard nav, which is apparently broken right now (not setting a default focus; works if you click a control).

Investigating in an emulator.

**Comment by BradyBrenot** [comment]
Emulator's running, confirmed it's hosed. Trying to figure out what I can do with it.

**Comment by Collisionc** [comment]
I'll try installing it to my shield tv and see if anything is different, it's probably broken there as well but it's worth a shot.

**Comment by dtanquary** [comment]
Just tested the new build on the fire tv. The arrow navigation is now working but I am not able to select anything.

**Comment by BradyBrenot** [comment]
Sigh, you'd think I would have tried that but nope. It's a little hard given that I can't seem to even get the emulator talking with my bridge.

Going to see if I can figure out what key Qt thinks that center button is, and then see if I can get it to act like Spacebar on the PC... somehow...

**Comment by dtanquary** [comment]
If it helps I am pretty sure the center button is the same thing as pressing "A" (KEYCODE_BUTTON_A) on any connected controller: https://developer.amazon.com/docs/fire-tv/remote-input.html#capturing-input

**Comment by BradyBrenot** [comment]
It's "Enter" in the AVD (as far as Qt sees it). Will see...

**Comment by BradyBrenot** [comment]
k @dtanquary I've added a new release with this "force the enter key to fire a spacebar event" hack. It definitely works in the AVD now, which is how Amazon recommends testing it, so it _really_ ought to work.

**Comment by Collisionc** [comment]
Shield TV works fine with it, although the UI doesn't scale very well as there doesn't seem to be a way to scroll down the app screen to see "Center Slowness" and "Side Slowness".  
![mvimg_20180325_023807_exported_8670243072523810912](https://user-images.githubusercontent.com/7837280/37872503-1f3d981a-2fd7-11e8-9f54-648de061cf8e.jpg)


Unrelated to this issue, but I do have to sideload the .apk to get it to work, and even when sideloaded it doesn't show up as an app anywhere, I have to go into settings --> apps ---> app details and select hustacean, and then open it there -- where it doesn't save anything from the previous session, so I have to relink the bridge. 

As far as DRM protected stuff goes, youtube/espn are working fine with huestacean.

**Comment by BradyBrenot** [comment]
Frame time jumping around is probably OK, Android doesn't actually seem to send frames unless something's changing on the screen.

**Comment by BradyBrenot** [comment]
And as far as playing Netflix goes, rooting + installing Xposed + installing the DisableSecureFlag extension seems to be the only way (I'm playing a video on Netflix right now on my phone and it's working). I can't recommend Xposed to users generally given how potentially dangerous it is but eh it exists.

**Comment by dtanquary** [comment]
@BradyBrenot I just tested out the latest build on the fire tv. I was able to navigate and select things for the most part but there are still 1 or 2 buttons that seem impossible to navigate to. I will try to make a little video of me navigating around and put it on youtube for you to see where I am getting stuck.

The firetv also seems to be killing the background process off nearly immediately after I navigate away from the app but that's a separate issue and I will see if there is anything I can tweak on the fire tv to control that. I may end up having to root to get the optimal experience but that would be worth it imo.

**Comment by Collisionc** [comment]
It might be a matter of processing power difference between the shield and fire tv. The fire tv is likely suspending everything that's in the background to reserve processing time for the foreground. Shield on the other hand has the capability of hosting a plex server + smartthings hub while playing media. 

You'd definitely be able to get around it via rooting the five tv, but it might not be the best experience if processing power is the issue.

**Comment by BradyBrenot** [comment]
Setting the app up to act as a Foreground Service might help, see

https://developer.amazon.com/docs/fire-tv/faq-general.html
https://developer.android.com/reference/android/app/Service.html

**Comment by BradyBrenot** [comment]
Which means reworking a good chunk of this thing to separate the GUI from the rest, which is... probably a good idea for all sorts of reasons, but a huge pain in the neck.

**Comment by mrmidnight273** [comment]
Installed on my Sony X900E. App starts and I can select stuff. Only issue I have is the syncing doesn't stick when I switch from the app to anything else (including Android TV home screen)

**Comment by BradyBrenot** [comment]
Split the foreground service thing off to #68 / #69

**Comment by mrmidnight273** [comment]
2.3 release won't allow me to click the link button. I can't even select it. Sony X900E

**Comment by BradyBrenot** [comment]
Folded into #126
