### ISSUE TITLE
Android TV - Process dies when backgrounded on Fire TV

### ISSUE THREAD

**Issue by BradyBrenot** [BradyBrenot/huestacean#68]
The only way I can figure to get around this is to split the backend and frontend off into separate processes, then make the backend a Foreground Service.

**Comment by koying** [comment]
It doesn't have to be different processes (in the applicative understanding).
All activities of an app run in the same process.
You "only" have to create a GUI activity and a hue handling Foreground service, but they share the same process.

**Comment by BradyBrenot** [comment]
Folded into #126
