### ISSUE TITLE
Add an icon

### ISSUE THREAD

**Issue by BradyBrenot** [BradyBrenot/huestacean#74]

**Comment by Menacer95** [comment]
![4f095a9f-07af-4714-9042-ee3f898739ef](https://user-images.githubusercontent.com/15659854/38775048-a03d4bb2-402c-11e8-935e-c7fa8a0dd1e8.jpeg)

i tried my best its decent for now :)

**Comment by PascalAOMS** [comment]
Anything design-wise in mind? I could help.

**Comment by Dracrius** [comment]
![huestacean](https://user-images.githubusercontent.com/26284634/40631225-0d9ca634-62b1-11e8-82b7-4017dc72463f.png)
This is what I use atm. I could easily make some tweaks. I also thought about the silhouette of the same icon cut out of a simple black monitor/tv with a spectrum glow around the exterior.

**Comment by BradyBrenot** [comment]
https://github.com/BradyBrenot/huestacean/blob/master/resources/images/icon.png

Not 100% on it but it's, uh, unique?

**Comment by davericher** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/908debe9-6ffa-4f73-b040-a8ff5f2595a3-ccf615f6-0651-4c0c-9730-f1a16d5342d4-v1.png?transparent=1&palette=1&width=246)
Happy to see the progress man, keep up the good work!
