### ISSUE TITLE
Hue White & Colour Ambiance bulb Stopped Syncing with 2.5

### ISSUE THREAD

**Issue by Dracrius** [BradyBrenot/huestacean#81]
I just updated from 2.0 to 2.5 so I'm sorry if this happened in a past update you've been busy! It may not be as easy to find the culprit. 

I have two entertainment groups one which only includes my lightstrip plus and one which contains it and my office ceilings Hue White & Colour Ambiance bulb. I usually only use the lightstrip but with all the updates it looked amazing after I tweaked the settings so I wanted to see what the whole room would look like. Unfortunately no matter what I do I can not get that ceiling light to work with huestacean after updating. If I select the group that contains both lights my ceiling light just turns off and remains unresponsive to my hue switch just like when it was actively syncing but it stays off even when on white web sites like this one.

**Comment by Dracrius** [comment]
No I tested it with both monitors on my desktop, this literal web page in firefox and a 16x9 (no bars) game play through of subnautica.

**Comment by BradyBrenot** [comment]
Yeah, this is weird, I've never seen just _one_ light fail.

Is the light positioned in the same place in the scene on the right as lights that are working?

How many lights are there total?

Does anything happen if you drag the "Saturation multiplier" down to zero, or drag min brightness up to 100%?

Is the light working in the iOS/Android app (if you go to Entertainment Groups, and then press on the light so it starts flashing)?

**Comment by Dracrius** [comment]
Alright Testing Stage 1 results:

Lights are positioned the same as the scene on the right.

There are 2 lights in the group I am trying to use. Full system/ through out the house are 11 lights in total but only these two are in an entertainment group.

Saturation down to zero changed nothing but raising the min brightness instantly lite up the bulb but it wont change colors. It will just light up white at whatever I set min brightness to while the lightstrip is going along with video's fine.

Last thing I did was run through the Philips "Test Area" setting for that group and the bulb responds perfectly to that test. I also opened up the copy of 2.0 I still had and it still works fine so something broke between 2.0 and 2.5. 

I won't have time tonight but if you need me to I can test the other 4 builds tomorrow to see when exactly it was introduced.

**Comment by Collisionc** [comment]
Yeah, something is a bit off, as only 1 of the 6 lights is updating when I run huestacean 2.5.

In my case I have 5 bulbs + 1 lightstrip and only 1 of the bulbs is updating.

**Comment by Kinematic9** [comment]
Hi, I am also running into issues with 2.5. I have a 'PC Group' that includes 2 bulbs, one to either side / rear of the monitor. Prior to 2.2, everything was perfect. 2.4 made things brighter/more sensitive for the screen, and now with 2.5 only the left one turns on and reacts, the right one just turns off.

**Comment by BradyBrenot** [comment]
Well that narrows it to one version, and for that matter one commit.

I haven't *used* 2.5 as much as I usually do yet, I'll see what I can see today before the ice storm rolls in and kills my power. If I'm lucky I can just reproduce the issues too

**Comment by BradyBrenot** [comment]
Got it, there's some straight-up stupidity happening here on my part.

I calculate the time that's passed since the last light update:
```		static QElapsedTimer timer;
		double deltaTime = timer.restart() / 1000.0;
		if (deltaTime > 1.0 || deltaTime <= 0.0 || std::isnan(deltaTime)) {
			deltaTime = 1.0;
		}
```

But, being a genius and all, I do this _per light_. Roughly looks like:
```
timer := new QElapsedTimer
loop
  for every light
    deltaTime = timer.restart()
    update light using deltaTime
  sleep 15ms
````

So the deltaTime is right for the _first light_ per update (~15ms), but not for any that follow (since they're each restarting the timer).

**Comment by Dracrius** [comment]
Perfect thank you again for a quick resolution.
