### ISSUE TITLE
Support for Chromecast on Android

### ISSUE THREAD

**Issue by GrimDeclaw** [BradyBrenot/huestacean#84]
Hi!
First of all : thanks and congrats for huestacean, it's an amazing piece of software!

One thing that would be great, but I guess definitely not an easy one : support for Chromecast (at least on Android).
That would be amazing as I guess I must not be the only one using a Chromecast to watch video from Android on my TV (and not hooking any HDMI cable), and because when doing so nothing change on the Android device screen huestacean doesn't pick anything changing (not a surprise btw).
I don't know if any lib exists for capturing Chromecast output on Android, and I'm guessing you have more important stuff to add/improve before this, but if you could keep this in your mind, and, some day ... who knows ^^

**Comment by banksio** [comment]
I'd think this would be quite hard because Chromecasts just run a web frame with the content inside. Maybe if huestacean could cast the screen and extract the colours? But then Chromecast would be using the screen capture protocol.

**Comment by GrimDeclaw** [comment]
That's what I guessed. Never looked deeper into it, kind of hoped for an Android API like "getChromeCastFrame" but that's definitely not the case.
Maybe by using the mirroring functionality of the home app, but from what I've tested, performance are way worst than "in app casting" like Youtube, Twitch, VLC or lots of chromecasting exiting apps.
Thanks again for your time!

**Comment by banksio** [comment]
@GrimDeclaw Yeah I'm not too experience on this though, maybe @BradyBrenot (dev) will know.

**Comment by Collisionc** [comment]
Very unlikely that this would work, as when you "cast" something to the chromecast, it actually just tells the server to redirect the video stream to the chromecast, bypassing the remote you are using.

**Comment by BradyBrenot** [comment]
Yeah, as far as I'm aware this isn't possible, so going to close this for now.
