### ISSUE TITLE
[UI/Win10] Navigation behind Title Bar  

### ISSUE THREAD

**Issue by PascalAOMS** [BradyBrenot/huestacean#89]
![](https://image.ibb.co/g3Ouin/ui_issue.jpg)

Downloaded the Windows .exe file.
Windows Smart Defender labeled it as non-secure beforehand.

**Comment by BradyBrenot** [comment]
What the. Anything particular about your setup, like running at an odd DPI or anything? Are you using the latest release (2.6)? I test on Windows 10, most people are probably using 10, this is the first report of this that I've received.

**Comment by PascalAOMS** [comment]
1440p resolution on 24".
Clean Windows install. Latest Windows 10 version.

It was a fresh download, so must have been the newest version of your software.

If I'm really the only one having this problem, don't worry about it. I can still use it. 😄

**Comment by BradyBrenot** [comment]
Can't repro, not sure if it's going to reoccur in new GUI or not.
