### ISSUE TITLE
Please Optimize for Android TV (Fire TV)

### ISSUE THREAD

**Issue by SmoothMC** [BradyBrenot/huestacean#91]
testet Versions 2.6
and 2.0. Alpha 3.1

both Versions
- conntect to bridge works fine
- start sync crash the app
- after restart all settings gone

please fix it ...i think it is more meaningful running this app on android tv than a android tablet ;) especially for watching Video content :)

greats

**Comment by BradyBrenot** [comment]
That's the intention, eventually, I just haven't been working on this too much recently. I need to pick up a Fire TV or an Android TV device too.

**Comment by willbeeching** [comment]
@BradyBrenot I love this app. I run it on my Nvidia Shield, it would be great if it could be run as a system service so that if the Shield is on, it runs and starts syncing. Then stops syncing if the shield is off.

Happy to donate a new Fire TV if it helps with your Android dev 😊

**Comment by fti7** [comment]
@BradyBrenot 
Same for me. Its an awesome app :-) 
Works like an charm for (at least) some Minutes on my Nvidia Shield - But it will be killed after a while due lack of an Background Service 😢 

Can we help you somehow? I guess we find enough people to collect money for Hardware 😄

**Comment by Maltyz** [comment]
Hey, i'm an android developper and i could help you to update / fix this tv version if you want.
Like others said, it works only for few minutes, but there's almost no delay, it's awesome !

**Comment by fti7** [comment]
@Maltyz that would be really nice :-)
It looks like BradyBrenot is really busy. His last commit here was in July :-(

**Comment by Ell223** [comment]
I've also been looking at this. But having trouble getting it to build- as I've not used Qt before. It's a shame because when this works, it works really well!

**Comment by Maltyz** [comment]
Yeah same problem here. I'll try more this week-end :)

**Comment by overdrive69** [comment]
On my sony android TV it only workes when i am directly in the app. As soon I leave the up (but running in the background) the light sync stops.
It would be so great the have this working.

**Comment by fti7** [comment]
There is an alternative App "Hue Stream" (https://play.google.com/store/apps/details?id=com.bullbash.huestream) which works in my case more reliable :-) Unfortunately the possibilities and color quality are much bigger on huesteacean

**Comment by overdrive69** [comment]
Yes this is working in the background on sony android tv.
Do you know is there a github site for this app?

**Comment by fti7** [comment]
Nope, i dont think its Opensource :-(

**Comment by BradyBrenot** [comment]
Rolling all Android TV / Fire TV issues into #126
