### ISSUE TITLE
Anything to learn from Hue Sync?

### ISSUE THREAD

**Issue by BradyBrenot** [BradyBrenot/huestacean#92]
1. The 'include audio with screen sync' feature is neat. I don't know that I like it, but it's neat.
2. Don't like their audio effect (it's very not mellow), but the colour palette thing is nice.
3. The GUI is very nice. I like the very simple set of options. Could lean on that a bit.
4. Keyboard shortcuts!
5. Light color selection. At times not great, at times pretty great. Lights on the edge of the screen are affected by black bars (mind the same is true in Huestacean so eh)
6. Brightness changes are slowed but hue/saturation seem to be immediate, always, even on 'subtle'. Not sure that I like. Side lights change color more slowly, but snap to change? Odd.

Honestly I think I'm more charged after seeing Sync. I think my niche isn't _that_ threatened.

**Comment by BradyBrenot** [comment]
https://i.imgur.com/eKnjk0K.jpg

**Comment by anthonyg45157** [comment]
Im liking your implementation better overall. Some stuff from Hue can be learned such as syncing on boot and program being minimized to task bar. Overall i like having more control which is what i believe you program offers.

**Comment by hoksilato2** [comment]
Shortcuts of Hue Sync are ok but not work with powershell, eventghost or some program that can emulate it. Command line should be the best feature for auto-open Hue light with games and/or multimedia soft.

**Comment by Dracrius** [comment]
I instantly uninstalled sync only thing I want that it had is keyboard shortcuts! This is more reactive and configurable. I get far better lighting effects with your implementation.

**Comment by darkzbaron** [comment]
Music sync with custom color palette would be nice !

**Comment by BradyBrenot** [comment]
I don't know what's left here. 

#101 - Keyboard shortcuts
#17 - Audio visualizer
#117 - GUI will take _some_ hints from Sync / the Hue App itself (mostly in color use and simplicity)
