### ISSUE TITLE
mi box 3 : app crash  

### ISSUE THREAD

**Issue by todely** [BradyBrenot/huestacean#95]
Hello,

First i wanna thanks Brady for his work.
I have try latest Android release on my Mi Box 3 (Android TV 7)

connexion with HUE hub is ok, all lights are in list and space configuration is found.

Problem: 
- There is no "display" to select in monitor list, but when click on start sync and use preview there is something inside preview box.
- When i'm in gui and go out to start Plex or anythings else, app crash.

 hop see a new release soon !

**Comment by BradyBrenot** [comment]
Folding into #126
