### ISSUE TITLE
Support for 32-bit Windows?

### ISSUE THREAD

**Issue by harakan2** [BradyBrenot/huestacean#99]
Is there a fundamental reason why only 64-bit Windows is supported?

I have a Windows Media Center, running Windows 8.1 32-bit (originally due to driver issues with the tuner card on 64-bit platforms). I'd really like to use this on there - I can't upgrade to Windows 10 and use the official Philips Hue Sync app as WMC is no longer in the OS. Will this work on Windows 8.1 32-bit?

**Comment by harakan2** [comment]
I compiled 32-bit myself from source. It does run and controls the lights based on screen content in windowed mode, but unfortunately they just turn off when running Media Center full screen.

**Comment by BradyBrenot** [comment]
No fundamental reason, no. Just a general reluctance to increase the number
of configurations I'm supporting due to workload.

The DXGI frame capture API is blocked by certain applications, including
e.g. the UWP Netflix app.
